networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=1
    - CLI_SERVER_ADDRESS=server:12345
    - CLI_LOOP_LAPSE=1m2s
    - CLI_LOOP_PERIOD=10s
    image: client:latest
    networks:
    - testing_net
  client2:
    container_name: client2
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=2
    - CLI_SERVER_ADDRESS=server:12345
    - CLI_LOOP_LAPSE=1m2s
    - CLI_LOOP_PERIOD=10s
    image: client:latest
    networks:
    - testing_net
  client3:
    container_name: client3
    depends_on:
    - server
    entrypoint: /client
    environment:
    - CLI_ID=3
    - CLI_SERVER_ADDRESS=server:12345
    - CLI_LOOP_LAPSE=1m2s
    - CLI_LOOP_PERIOD=10s
    image: client:latest
    networks:
    - testing_net
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - SERVER_IP=server
    - SERVER_PORT=12345
    - SERVER_LISTEN_BACKLOG=5
    image: server:latest
    networks:
    - testing_net
version: '3'
